### ISSUE TITLE
Pooped block stay in place

### ISSUE THREAD

**Issue by Floodo** [AliDanger2/Poop#1]
Hello there :) ... I have an issue on my Paper server v1.21.3 with Poop v2.4. After like 20 diarrhea command it stops replacing block back, soo the world is full of brown block.. In console I get this warn. Can you help with it? Is there some safe command, that can replace the blocks back?

https://pastes.dev/KXLo0Boyfe

EDIT: Probably it happend when you are sitting on a horse (or boat), and then you press shift with activated diarrhea, soo you are standing on feet but diarrhea launched you in the skye, and then it gives warn in console, and the land is brown for ever (until someone will mine it, and replace those blocks) 

EDIT 2: If one player teleport to another player, and both didn't move, and one of them will do /diarrhia and shift, it will also do warn in console (as i place it above) and blocks will stay brown, and would not be replaced again.

**Comment by AliDanger2** [comment]
Hello sorry for the late response it was because of the exams and i didn't have much time to work on the plugin i'll start addressing the problem from now thanks for reporting it <3

**Comment by HshanLove** [comment]
[poop] Task #91323 for poop v2.4 generated an exception
java.lang.IllegalArgumentException: x not finite
        at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.util.Vector.checkFinite(Vector.java:872) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.entity.CraftEntity.setVelocity(CraftEntity.java:146) ~[paper-1.21.4.jar:1.21.4-231-09e9afd]
        at 【拉屎】poop-2.4.jar/me.poop.poop.Poop.launchNearbyEntities(Poop.java:690) ~[【拉屎】poop-2.4.jar:?]
        at 【拉屎】poop-2.4.jar/me.poop.poop.Poop.executeDiarrheaExplosion(Poop.java:582) ~[【拉屎】poop-2.4.jar:?]
        at 【拉屎】poop-2.4.jar/me.poop.poop.Poop.lambda$onPlayerSneakForDiarrhea$4(Poop.java:554) ~[【拉屎】poop-2.4.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-231-09e9afd]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.4.jar:1.21.4-231-09e9afd]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1659) ~[paper-1.21.4.jar:1.21.4-231-09e9afd]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1529) ~[paper-1.21.4.jar:1.21.4-231-09e9afd]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[paper-1.21.4.jar:1.21.4-231-09e9afd]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-231-09e9afd]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

I have the same problem as well.
